#!/usr/bin/env bash

NR1_IMAGE="${NR1_IMAGE:-nr1-in-docker}"

# First, ensure that a docker image exists for nr1-in-docker
IMAGE_EXISTS="$(docker image inspect "$NR1_IMAGE" >/dev/null 2>&1; echo $?)"
if [ "$IMAGE_EXISTS" -ne 0 ]; then
  echo "Building a docker image for nr1: $NR1_IMAGE" >&2
  SCRIPT_PATH=$(dirname "$(realpath -s "$0")")
  docker build "$SCRIPT_PATH" --tag "$NR1_IMAGE" >&2 || exit $?
fi

# Now run the script!
# TODO: Figure out how to expose the proper ports (perhaps 9972 and 5000)
docker run -it --volume ~/.newrelic:/root/.newrelic --volume "$(pwd):/nerdpack" "$NR1_IMAGE" "$@"
