#!/usr/bin/env bash

# This script should stop running if any line ends with a non-zero status
set -e

NR1_PROFILE='nr1-in-docker'

# Inject nr1 secrets into the container
nr1 profiles:add --name "$NR1_PROFILE" --api-key "$NR1_API_KEY" --region "$NR1_REGION"

# Go to where the Nerdpack code lives
# See https://help.github.com/en/articles/virtual-environments-for-github-actions#environment-variables
cd "$GITHUB_WORKSPACE"

# Publish the Nerdpack
nr1 nerdpack:publish --profile="$NR1_PROFILE" --verbose

# Then, at long last, deploy the Nerdpack!
nr1 nerdpack:deploy --channel="$NR1_CHANNEL" --verbose
